docker run -d `
  --name emqx `
  --hostname node1.emqx.com `
  -e "EMQX_NODE_NAME=emqx@node1.emqx.com" `
  -p 1883:1883 `
  -p 8083:8083 `
  -p 8084:8084 `
  -p 8883:8883 `
  -p 18083:18083 `
  emqx/emqx-enterprise:6.3.1